### ISSUE TITLE
nginx.conf

### ISSUE THREAD

**Issue by jota-coelho** [evanshortiss/s2i-nodejs-nginx#4]
Hi...
I create a nginx.conf into .s2i/nginx... But this file do not overwrite the original nginx.conf

I trying to overwrite a file .s2i/bin/setup-nginx-conf, but too not successful

**Comment by evanshortiss** [comment]
@jota-coelho I've confirmed this is an issue. Pushing a patch soon!

**Comment by evanshortiss** [comment]
Can you try again? It's working for me now. Make sure you podman/docker pull the updated tag(s) you're using.

**Comment by evanshortiss** [comment]
@jota-coelho feel free to reopen this issue if the patched images are not working for you.
